webtalk_init -webtalk_dir C:/Users/chris/Documents/git-repos/fpga_emb_drone/FPGA_drone/FPGA_drone.sim/sim_1/behav/xsim/xsim.dir/tb_receiver_control_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 24 12:48:34 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dfaa7123-20d4-42c6-b19b-b5aa879b29ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "319caf9d199f4393b3cc4babf07f467f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6048_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4136445188 -regid "" -xml C:/Users/chris/Documents/git-repos/fpga_emb_drone/FPGA_drone/FPGA_drone.sim/sim_1/behav/xsim/xsim.dir/tb_receiver_control_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/chris/Documents/git-repos/fpga_emb_drone/FPGA_drone/FPGA_drone.sim/sim_1/behav/xsim/xsim.dir/tb_receiver_control_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/chris/Documents/git-repos/fpga_emb_drone/FPGA_drone/FPGA_drone.sim/sim_1/behav/xsim/xsim.dir/tb_receiver_control_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
